// Tengwar for the Omarchy bar -- part of the Fellowship theme.
//
// GENERATED by forge/barwidget.py. Edit that, not this.
//
// Quenya set in Tengwar Annatar, which uses Daniel Smith's keyboard-position
// encoding: the strings below look like line noise in any other font because
// the tengwar are deliberately "in the wrong places". They were transcribed by
// forge/tengwar.py, never typed by hand.
//
// Placed either side of omarchy.clock, the two default phrases read as one
// sentence with the time inside it:
//
//     elen sila  <clock>  omentielvo
//     "a star shines upon the hour of our meeting"
//
// Usage in ~/.config/omarchy/shell.json, under bar.layout.center:
//
//   { "id": "tengwar-left", "type": "qml",
//     "source": "~/.config/omarchy/bar/modules/tengwar.qml",
//     "phrase": "elen-sila" }
//
// Settings: phrase (key from the table below), size, opacity, color.
import QtQuick

Item {
  id: root

  property var bar
  property string moduleName
  property var settings

  readonly property var phrases: {
      "elen-sila": {
          "tengwar": "`Fj$5 8~Gj#",
          "latin": "elen síla",
          "gloss": "Elen síla lúmenn' omentielvo — a star shines upon the hour of our meeting"
      },
      "omentielvo": {
          "tengwar": "`Ht$4%`FjyY",
          "latin": "omentielvo",
          "gloss": "Elen síla lúmenn' omentielvo — a star shines upon the hour of our meeting"
      },
      "sinome-maruvan": {
          "tengwar": "iT5^t$ t#7UyE5",
          "latin": "sinome maruvan",
          "gloss": "Sinome maruvan — here I will abide (Elessar, at his crowning)"
      },
      "utulien-aure": {
          "tengwar": "`J1~Jj%`F5 `D`J7R",
          "latin": "utúlie'n aurë",
          "gloss": "Utúlie'n aurë — day has come (Fingon, before the Nirnaeth)"
      },
      "auta-i-lome": {
          "tengwar": "`D`J1E `G j~Ht$",
          "latin": "auta i lómë",
          "gloss": "Auta i lómë — the night is passing"
      },
      "namarie": {
          "tengwar": "5#t~D7T`F",
          "latin": "namárië",
          "gloss": "Namárië — farewell"
      }
  }

  readonly property var phrase: {
    var k = settings && settings.phrase ? settings.phrase : "elen-sila"
    return phrases[k] !== undefined ? phrases[k] : phrases["elen-sila"]
  }

  // Tengwar Annatar is AUR-only (ttf-tengwar-annatar). Without it the keying
  // would render as Latin gibberish, so the module stands down instead: it
  // reports zero width and the bar closes the gap as if it were not there.
  readonly property bool haveFont: Qt.fontFamilies().indexOf("Tengwar Annatar") >= 0

  // A vertical bar is 28px wide and these phrases are long; they only work
  // along a horizontal edge.
  readonly property bool usable: haveFont && !(bar && bar.vertical)

  // Click to read it in Latin letters.
  property bool romanised: false

  visible: usable
  implicitWidth: usable ? label.implicitWidth + 18 : 0
  implicitHeight: bar ? bar.barSize : 26

  Text {
    id: label
    anchors.centerIn: parent
    // The tengwar sit high in the em box; nudge them onto the bar's optical
    // centre rather than its geometric one.
    anchors.verticalCenterOffset: root.romanised ? 0 : Math.round(font.pixelSize * 0.10)

    text: root.romanised ? root.phrase.latin : root.phrase.tengwar
    font.family: root.romanised ? (root.bar ? root.bar.fontFamily : "monospace")
                                : "Tengwar Annatar"
    font.pixelSize: root.romanised
      ? Math.round((root.settings && root.settings.size ? root.settings.size : 17) * 0.62)
      : (root.settings && root.settings.size ? root.settings.size : 17)
    color: (root.settings && root.settings.color)
      ? root.settings.color
      : (root.bar ? root.bar.foreground : "white")
    opacity: (root.settings && root.settings.opacity !== undefined)
      ? root.settings.opacity : 0.72
    renderType: Text.NativeRendering
  }

  MouseArea {
    anchors.fill: parent
    hoverEnabled: true
    acceptedButtons: Qt.LeftButton
    onEntered: if (root.bar) root.bar.showTooltip(root, root.phrase.gloss)
    onExited: if (root.bar) root.bar.hideTooltip(root)
    onClicked: root.romanised = !root.romanised
  }
}
