#!/usr/bin/env python3
"""Write the tengwar bar module.

    python3 barwidget.py [out.qml]

The Omarchy bar loads custom modules as plain QML with no way to run Python at
paint time, so the tengwar keyings are baked in here rather than transcribed
live.  They come from tengwar.py, which checks itself against the font's own
documentation first, so the strings in the generated file are never hand-typed.

The bar carries one phrase either side of the clock:

    elen sila   ...   [ the clock ]   ...   omentielvo

which is Frodo's greeting to Gildor -- *elen sila lumenn' omentielvo*, "a star
shines upon the hour of our meeting".  The clock stands where *lumenn'*, "upon
the hour", belongs, so the bar reads as one sentence with the time inside it.
"""
import sys, json
from tengwar import transcribe, self_test

PHRASES = {
    "elen-sila": (
        "elen síla",
        "a star shines",
        "Elen síla lúmenn' omentielvo — a star shines upon the hour of our meeting",
    ),
    "omentielvo": (
        "omentielvo",
        "of our meeting",
        "Elen síla lúmenn' omentielvo — a star shines upon the hour of our meeting",
    ),
    "sinome-maruvan": (
        "sinome maruvan",
        "here I will abide",
        "Sinome maruvan — here I will abide (Elessar, at his crowning)",
    ),
    "utulien-aure": (
        "utúlie'n aurë",
        "day has come",
        "Utúlie'n aurë — day has come (Fingon, before the Nirnaeth)",
    ),
    "auta-i-lome": (
        "auta i lómë",
        "the night is passing",
        "Auta i lómë — the night is passing",
    ),
    "namarie": (
        "namárië",
        "farewell",
        "Namárië — farewell",
    ),
}

TEMPLATE = '''// Tengwar for the Omarchy bar -- part of the Fellowship theme.
//
// GENERATED by forge/barwidget.py. Edit that, not this.
//
// Quenya set in Tengwar Annatar, which uses Daniel Smith's keyboard-position
// encoding: the strings below look like line noise in any other font because
// the tengwar are deliberately "in the wrong places". They were transcribed by
// forge/tengwar.py, never typed by hand.
//
// Placed either side of omarchy.clock, the two default phrases read as one
// sentence with the time inside it:
//
//     elen sila  <clock>  omentielvo
//     "a star shines upon the hour of our meeting"
//
// Usage in ~/.config/omarchy/shell.json, under bar.layout.center:
//
//   {{ "id": "tengwar-left", "type": "qml",
//     "source": "~/.config/omarchy/bar/modules/tengwar.qml",
//     "phrase": "elen-sila" }}
//
// Settings: phrase (key from the table below), size, opacity, color.
import QtQuick

Item {{
  id: root

  property var bar
  property string moduleName
  property var settings

  readonly property var phrases: {phrases}

  readonly property var phrase: {{
    var k = settings && settings.phrase ? settings.phrase : "elen-sila"
    return phrases[k] !== undefined ? phrases[k] : phrases["elen-sila"]
  }}

  // Tengwar Annatar is AUR-only (ttf-tengwar-annatar). Without it the keying
  // would render as Latin gibberish, so the module stands down instead: it
  // reports zero width and the bar closes the gap as if it were not there.
  readonly property bool haveFont: Qt.fontFamilies().indexOf("Tengwar Annatar") >= 0

  // A vertical bar is 28px wide and these phrases are long; they only work
  // along a horizontal edge.
  readonly property bool usable: haveFont && !(bar && bar.vertical)

  // Click to read it in Latin letters.
  property bool romanised: false

  visible: usable
  implicitWidth: usable ? label.implicitWidth + 18 : 0
  implicitHeight: bar ? bar.barSize : 26

  Text {{
    id: label
    anchors.centerIn: parent
    // The tengwar sit high in the em box; nudge them onto the bar's optical
    // centre rather than its geometric one.
    anchors.verticalCenterOffset: root.romanised ? 0 : Math.round(font.pixelSize * 0.10)

    text: root.romanised ? root.phrase.latin : root.phrase.tengwar
    font.family: root.romanised ? (root.bar ? root.bar.fontFamily : "monospace")
                                : "Tengwar Annatar"
    font.pixelSize: root.romanised
      ? Math.round((root.settings && root.settings.size ? root.settings.size : 17) * 0.62)
      : (root.settings && root.settings.size ? root.settings.size : 17)
    color: (root.settings && root.settings.color)
      ? root.settings.color
      : (root.bar ? root.bar.foreground : "white")
    opacity: (root.settings && root.settings.opacity !== undefined)
      ? root.settings.opacity : 0.72
    renderType: Text.NativeRendering
  }}

  MouseArea {{
    anchors.fill: parent
    hoverEnabled: true
    acceptedButtons: Qt.LeftButton
    onEntered: if (root.bar) root.bar.showTooltip(root, root.phrase.gloss)
    onExited: if (root.bar) root.bar.hideTooltip(root)
    onClicked: root.romanised = !root.romanised
  }}
}}
'''


def main():
    self_test()
    table = {
        key: {"tengwar": transcribe(latin), "latin": latin, "gloss": gloss}
        for key, (latin, gloss, _) in
        ((k, (v[0], v[2], None)) for k, v in PHRASES.items())
    }
    body = json.dumps(table, ensure_ascii=False, indent=4)
    body = "\n".join(("  " + ln) if i else ln for i, ln in enumerate(body.splitlines()))
    out = sys.argv[1] if len(sys.argv) > 1 else "tengwar.qml"
    with open(out, "w") as fh:
        fh.write(TEMPLATE.format(phrases=body))
    print("wrote", out)


if __name__ == "__main__":
    main()
